# Generated by Django 4.0 on 2021-12-16 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='media_status',
            field=models.BooleanField(default=False),
        ),
    ]
