# Generated by Django 4.0 on 2021-12-16 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_media_media_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='mediacatagory',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='mediacatagory1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='mainapp.mediacatagory'),
        ),
    ]
