# Generated by Django 4.0 on 2021-12-16 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0003_mediacatagory_media_mediacatagory1'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='fulltext',
            field=models.CharField(max_length=200),
        ),
    ]
